Порядок работы в notebook
1. Загрузить датасет
pd.read_csv, посмотреть df.head(), df.shape, df.dtypes
2. Описать датасет
Что за данные, сколько строк, какие поля
3. Почистить данные
df.isna().sum(), убрать NaN, проверить типы
4. Descriptive statistics
df.describe(), mean/median/std для 4 числовых полей
5. Простые графики
4 графика, 3 разных типа
6. Подробный анализ
4 сравнения — тут уже начинаешь замечать интересные связи
7. Трансформация
Добавить 1-2 новых колонки
8. Гипотезы
Вот здесь — после того как посмотрели на данные, выдвигаете 2 гипотезы и проверяете их графиками/статистикой
9. Discussion
После каждого блока пишете пару предложений что увидели

Flight Price Analysis
Kazykina Sofya & Gainullina Amina

In [16]:
import pandas as pd
import streamlit as st
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv('Clean_Dataset.csv')
df.head()

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955

In [5]:
df.tail()

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

Датасет содержит информацию о рейсах в Индии: авиакомпания, маршрут,
время вылета и прилёта, количество пересадок, класс и цена билета.

Числовые поля: price, duration, days_left, num_stops
Категориальные поля: airline, source_city, destination_city, departure_time, class

In [8]:
df.shape

(300153, 12)

In [12]:
df.dtypes

Unnamed: 0            int64
airline                 str
flight                  str
source_city             str
departure_time          str
stops                   str
arrival_time            str
destination_city        str
class                   str
duration            float64
days_left             int64
price                 int64
dtype: object

In [22]:
df = pd.read_csv("Clean_Dataset.csv", index_col=0)
df.tail()

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

убрала колонку unnamed